
version: '3.8'

services:
  pushnotify-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Optional: Add a service to clone from GitHub if needed
  git-clone:
    image: alpine/git
    volumes:
      - ./:/app
    command: >
      sh -c "
        if [ ! -d '/app/.git' ]; then
          echo 'Cloning repository...'
          git clone https://github.com/Mr4rogrammer/push-connect-now.git /tmp/repo
          cp -r /tmp/repo/* /app/
          cp -r /tmp/repo/.* /app/ 2>/dev/null || true
        else
          echo 'Repository already exists'
        fi
      "
    profiles:
      - clone

